
logger:
  namespace: insolvency-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}

CHS_API_KEY:  ${CHS_KAFKA_API_URL:chsApiKey}

springfox:
  documentation:
    auto-startup: false