server:
  port: 8082

logger:
  namespace: insolvency-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}

springfox:
  documentation:
    auto-startup: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/local_db}
