
logger:
  namespace: insolvency-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/insolvency}
