
logger:
  namespace: insolvency-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/insolvency}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /insolvency-data-api
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true