
logger:
  namespace: insolvency-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/insolvency}

insolvency:
  transactions: ${TRANSACTIONS_ENABLED:false}

