
logger:
  namespace: insolvency-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false

insolvency:
  transactions: ${TRANSACTIONS_ENABLED:false}

